name:                memdb
version:             1.0.0.0
github:              "pkamenarsky/memdb"
license:             BSD3
author:              "Philip Kamenarsky"
maintainer:          "p.kamenarsky@gmail.com"
copyright:           "2018 Philip Kamenarsky"

extra-source-files:
- README.md
- ChangeLog.md
- cbits/Multimap.cpp

# Metadata used when publishing your package
synopsis:            Efficient in memory indexed database
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pkamenarsky/memdb#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cereal
- mmap
- vector
- ghc-compact
- vector-th-unbox

library:
  c-sources: cbits/Multimap.cpp
  cc-options: -O2
  extra-libraries: stdc++
  source-dirs: src
  exposed-modules:
  - Database.Immutable
  - Database.Immutable.Read
  - Database.Immutable.Read.Unboxed
  - Database.Immutable.Write
  - Multimap.ByteString
  - Multimap.Word32

executables:
  memdb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memdb

tests:
  memdb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memdb
