name:                memdb
version:             1.0.0.3
github:              "pkamenarsky/memdb"
license:             MIT
author:              "Philip Kamenarsky"
maintainer:          "p.kamenarsky@gmail.com"
copyright:           "2018 Philip Kamenarsky"

extra-source-files:
- README.md
- ChangeLog.md
- cbits/Multimap.cpp

# Metadata used when publishing your package
synopsis:            Efficient in memory indexed database
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pkamenarsky/memdb#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cereal
- containers
- deepseq
- generics-eot
- leveldb-haskell
- monoidal-containers
- validation
- vector

library:
  c-sources: cbits/Multimap.cpp
  cc-options: -O2 -std=c++11
  ghc-options:
  - -Wall
  extra-libraries: stdc++
  source-dirs: src
  exposed-modules:
  - Database.Immutable
  - Database.Immutable.Experimental
  - Database.Immutable.Experimental.Csv
  - Database.Immutable.Experimental.LevelDB
  - Database.Immutable.Read
  - Database.Immutable.Write
  - Multimap.ByteString
  - Multimap.Word32

tests:
  memdb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2
    - -Wall
    - -fno-warn-partial-type-signatures
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memdb
    - hspec
    - QuickCheck
